### ISSUE TITLE
外接屏幕时候只有主屏显示屏保

### ISSUE THREAD

**Issue by RoyXiBoy** [Planshit/ProjectEye#1]
外接屏幕时候只有主屏显示屏保

**Comment by thelittlepandaisbehind** [comment]
将在下一次更新中修复，谢谢反馈。

**Comment by thelittlepandaisbehind** [comment]
我会尝试在下一次更新中修复，谢谢反馈。

**Comment by thelittlepandaisbehind** [comment]
更新了，如果测试没问题希望能再次反馈一下谢谢。（我自己测试是没问题了）[https://github.com/Planshit/ProjectEye/releases/tag/v1.0.1](https://github.com/Planshit/ProjectEye/releases/tag/v1.0.1)

**Comment by thelittlepandaisbehind** [comment]
> 外接屏幕时候只有主屏显示屏保

@RoyXiBoy 更新了，如果测试没问题希望能再次反馈一下谢谢。（我自己测试是没问题了）[https://github.com/Planshit/ProjectEye/releases/tag/v1.0.1](https://github.com/Planshit/ProjectEye/releases/tag/v1.0.1)
