### ISSUE TITLE
建议增加白名单功能

### ISSUE THREAD

**Issue by ZhangSanMo** [Planshit/ProjectEye#12]
经常遇到打着打着游戏弹出框框，导致**打着游戏唱着歌，突然就被对面给杀了**的问题；
能否增加白名单功能，避免这种情况~

**Comment by thelittlepandaisbehind** [comment]
将在下一个版本更新中加入~

**Comment by thelittlepandaisbehind** [comment]
@ZhangSanMo 已经更新了~在1.1.3版本中加入了
