### ISSUE TITLE
建议增加修改倒计时背景色，白色太亮了

### ISSUE THREAD

**Issue by chenyinchao** [Planshit/ProjectEye#15]

**Comment by thelittlepandaisbehind** [comment]
谢谢你的建议。

正常来说，我认为倒计时页面理论上能被看到的时间应该不超过3秒，因为这个时候你该休息眼睛了，而不应该继续注视屏幕，所以倒计时界面可能不是特别重要。但是后续应该会加入完全自定义提醒界面UI的选项，我想再关注下这个需求有没有更多人需要吧。

关于太亮的问题，你可以尝试更换为暗色皮肤看看是否有帮助。

**Comment by thelittlepandaisbehind** [comment]
好吧我似乎搞错了，因为我开启了预提醒选项，到休息时间前只有一个小弹窗提示休息而不是直接弹出全屏窗口，所以我才会错误地认为倒计时页面不会被看到超过3秒。我会在下一次更新中加入完全自定义倒计时界面的选项~谢谢你的建议

**Comment by chenyinchao** [comment]
嗯，全屏白色倒计时太亮了，要是有灰色或自定义色就好了，这个软件真实用，以前也用过eyefoo，和workrave，还是这个好用些

**Comment by thelittlepandaisbehind** [comment]
@chenyinchao 更加方便的自定义倒计时界面功能已经发布，在最新版本 > 选项 > 显示 > 自定义中可以修改啦，右键空白的地方选择属性，可以修改倒计时背景色以及透明度~
