### ISSUE TITLE
多桌面显示有问题

### ISSUE THREAD

**Issue by master2vic** [Planshit/ProjectEye#16]
我使用DELL笔记本，使用的时候发下这个软件只有在笔记本的显示器上显示。但是其实我设置的主显示器是拓展屏幕。
同时在显示的时候是按照主屏幕（拓展屏幕的尺寸）而不是以笔记本的尺寸，在笔记本自带的显示器上显示。
我希望可以在所有桌面上出现提示。

**Comment by thelittlepandaisbehind** [comment]
非常抱歉，我无法复现这个问题。软件在很早的版本中就已加入了在所有屏幕上显示的支持。我测试使用的是thinkpad笔记本电脑，并且按照你的习惯把扩展显示器设为主显示器，测试中软件可以正常同时在所有显示器（桌面）上显示，除了预提醒弹窗有些问题且只能在主显示器上弹出外。

可能的原因：1，程序因某些问题没有正确检测或处理多个显示器；2，如果安装了安全软件可能是被安全软件拦截了（project eye在启动时会预先在所有屏幕上创建提示窗口，可能安全软件检测到看不见的窗口所以判定为病毒？），尝试关闭所有安全软件观察一下。

我将在下个版本加入一个暂定为系统信息导出的功能，以便于在遇到问题时可以在选项中导出一份能够帮助我定位问题的log，希望到时候能解决这个问题。

**Comment by master2vic** [comment]
好的谢谢啦，我会留意版本更新的

**Comment by master2vic** [comment]
那个不好意思了，这个是我的HDMI分线器的问题。我在切换电脑的时候使用的是HDMI分线器，但是这个分线器并没有正常工作，仅仅是图像信息投了过去，但是音频等信息并没有投放，所以产生的bug。
所以这个bug是我的HDMI分线器产生的，我去找他们聊天了。

**Comment by thelittlepandaisbehind** [comment]
没关系，也谢谢你，你提出问题后让我重新看了遍代码发现很多可以改进的地方。如果确定不是程序问题的话请关闭这个issue
