### ISSUE TITLE
开机后报错并闪退，附上日志

### ISSUE THREAD

**Issue by thisistianqi** [Planshit/ProjectEye#18]
[error_2019_12_04_08_52_53.log](https://github.com/Planshit/ProjectEye/files/3919434/error_2019_12_04_08_52_53.log)

（可以正常重新打开软件）

**Comment by thisistianqi** [comment]
win10 1903 x64

**Comment by thelittlepandaisbehind** [comment]
谢谢你的反馈。这个问题比较棘手，我的电脑系统版本跟你的一样，但是没能复现错误，我需要更多时间去定位问题。

你可以尝试下右键 projecteye.exe > 属性 > 兼容性 > 设置[勾选“以管理员身份运行此程序”] > 应用，然后重启看下是否还会报错，如果还是报错的话只能先关掉“离开监听”功能了，我会在下一个版本解决这个问题。ps:问题解决前请暂时不要关闭这个issue

**Comment by thelittlepandaisbehind** [comment]
注意，如果程序运行中开启了“离开监听”可能无法正常使用，在你离开电脑5分钟后会报错退出。

**Comment by thisistianqi** [comment]
刚才报错之后我直接重新运行软件，目前正常使用，如果还有报错我会再来上传日志，不是每次重启都会报错。

**Comment by thisistianqi** [comment]
> 谢谢你的反馈。这个问题比较棘手，我的电脑系统版本跟你的一样，但是没能复现错误，我需要更多时间去定位问题。
> 
> 你可以尝试下右键 projecteye.exe > 属性 > 兼容性 > 设置[勾选“以管理员身份运行此程序”] > 应用，然后重启看下是否还会报错，如果还是报错的话只能先关掉“离开监听”功能了，我会在下一个版本解决这个问题。ps:问题解决前请暂时不要关闭这个issue

我试啦，属性兼容性勾选管理员身份运行的话，开机自启就失效了，刚才重启了几次都没有自启。然后取消勾选管理员身份运行再重启，软件就可以自启了。

**Comment by thelittlepandaisbehind** [comment]
> > 谢谢你的反馈。这个问题比较棘手，我的电脑系统版本跟你的一样，但是没能复现错误，我需要更多时间去定位问题。
> > 你可以尝试下右键 projecteye.exe > 属性 > 兼容性 > 设置[勾选“以管理员身份运行此程序”] > 应用，然后重启看下是否还会报错，如果还是报错的话只能先关掉“离开监听”功能了，我会在下一个版本解决这个问题。ps:问题解决前请暂时不要关闭这个issue
> 
> 我试啦，属性兼容性勾选管理员身份运行的话，开机自启就失效了，刚才重启了几次都没有自启。然后取消勾选管理员身份运行再重启，软件就可以自启了。

自启后还有报错吗

**Comment by thisistianqi** [comment]
> > > 谢谢你的反馈。这个问题比较棘手，我的电脑系统版本跟你的一样，但是没能复现错误，我需要更多时间去定位问题。
> > > 你可以尝试下右键 projecteye.exe > 属性 > 兼容性 > 设置[勾选“以管理员身份运行此程序”] > 应用，然后重启看下是否还会报错，如果还是报错的话只能先关掉“离开监听”功能了，我会在下一个版本解决这个问题。ps:问题解决前请暂时不要关闭这个issue
> > 
> > 
> > 我试啦，属性兼容性勾选管理员身份运行的话，开机自启就失效了，刚才重启了几次都没有自启。然后取消勾选管理员身份运行再重启，软件就可以自启了。
> 
> 自启后还有报错吗

没有，安装到现在一共4天，还只出现过一次报错
