### ISSUE TITLE
提一些建议吧

### ISSUE THREAD

**Issue by tyskink** [Planshit/ProjectEye#19]
1. 更灵活的时间段
20分钟一到不必强制离开，可以延迟到35分钟，给保存文件，记录想法，收尾工作的时间，在此时间内只要鼠标停止工作就算休息成功。多工作的这0~15分钟，可以适当延长休息时间，或者从灵活时间分配中获取。例如半天下来之后发现
2。 回来提醒
玩太久不好，超过十分钟要提醒休息的太多
3. 发布到win store
4. 以注册win servers的形式，在action centre发出提醒。提供延迟和ok两个或者更多选项。
5. 区分工作时段和早中晚饭休息时段，或者上下午茶时段。

**Comment by thelittlepandaisbehind** [comment]
谢谢你提出这些很好的建议。

1:已加入开发计划；

2:我会尽快做准备；

3:已在开发计划中；

4:project eye的定位是一个用眼提示软件，我觉得用眼不应该区分工作或休息时段。

**Comment by mr-south-guo** [comment]
希望在“番茄时钟”模式时，系统托盘图标的提示，也能显示距离下个阶段的时间（象“常规”模式下那样）。目前是只显示第几阶段 [x/y]。

**Comment by thelittlepandaisbehind** [comment]
> 希望在“番茄时钟”模式时，系统托盘图标的提示，也能显示距离下个阶段的时间（象“常规”模式下那样）。目前是只显示第几阶段 [x/y]。

收到，在下一个版本中会加入
