### ISSUE TITLE
用了一段时间了，非常好！

### ISSUE THREAD

**Issue by dylanbai8** [Planshit/ProjectEye#2]
提几个建议：
1.看视频，电影的时候，20分钟弹出一次很烦。希望能自动检测。
2.弹出休息提示后，如果超过20秒没有点击按钮选项，则在检测到鼠标或者键盘有任何操作时自动关闭（像屏保那样）

**Comment by thelittlepandaisbehind** [comment]
@dylanbai8 

谢谢，建议已加入todolist

针对问题

1. 建议看电影的时候启用“不要提醒”，看完后再关闭；
