### ISSUE TITLE
睡眠或者休眠后再开电脑会强制休息，这就相当于延长了恢复开机的时间

### ISSUE THREAD

**Issue by thisistianqi** [Planshit/ProjectEye#20]
如题，睡眠或者休眠后恢复启动电脑的时候，就一定会休息20秒，相当于开机时间变长了，这就有点不方便了，不知道能不能解决这个问题？

**Comment by thelittlepandaisbehind** [comment]
是不是没有开启离开监听功能？

**Comment by thelittlepandaisbehind** [comment]
> 如题，睡眠或者休眠后恢复启动电脑的时候，就一定会休息20秒，相当于开机时间变长了，这就有点不方便了，不知道能不能解决这个问题？

谢谢反馈。下次更新的时候会解决这个问题

**Comment by thelittlepandaisbehind** [comment]
@thisistianqi 已经更新啦，下载最新版本即可~

**Comment by thisistianqi** [comment]
什么神仙效率，也太棒了吧
先关帖子了
