### ISSUE TITLE
关于数据统计和内存使用问题

### ISSUE THREAD

**Issue by mifenfeifen** [Planshit/ProjectEye#23]
# 数据统计问题
如果软件没有被关闭，数据统计会一直认为是开启当天。12日开启后，一直没关机，现在显示用眼已经180小时了……
![image](https://user-images.githubusercontent.com/16129288/72696201-5535f280-3b76-11ea-867f-6dca91bec963.png)

# 内存使用
这个简单的应用，就占用了100M以上的内存，感觉还是比较夸张了
![image](https://user-images.githubusercontent.com/16129288/72696262-844c6400-3b76-11ea-97f6-eb70afe2379b.png)

**Comment by thelittlepandaisbehind** [comment]
谢谢你的反馈，我会尽快修复这些问题。

**Comment by thelittlepandaisbehind** [comment]
已经发布了更新，如果有空测试一下~

**Comment by mifenfeifen** [comment]
> 已经发布了更新，如果有空测试一下~

@thelittlepandaisbehind 
好的，现在去尝试新版本

**Comment by thelittlepandaisbehind** [comment]
> > 已经发布了更新，如果有空测试一下~
> 
> @thelittlepandaisbehind
> 好的，现在去尝试新版本

如果已经解决问题请麻烦您关闭一下这个issue，相反，如果没有解决请继续提交问题~

**Comment by mifenfeifen** [comment]
@thelittlepandaisbehind 
内存占用先不说，数据统计的问题还是没修复好。今天是9号，依然是统计到6号去了。

另外，还发现了一个问题，双屏情况下，提示页面的自定义背景颜色无法统一。
![eye_protect_wrong](https://user-images.githubusercontent.com/16129288/76180056-d1a09580-61f7-11ea-9e60-42676fb7ecdc.png)

还有一个提议：选择颜色时的自定义颜色，希望可以保存。每次打开这个设置都要重新添加到自定义颜色然后才能使用

**Comment by thelittlepandaisbehind** [comment]
我更新了统计数据部分的代码，更新的软件在附件里，你下载再试试是否能解决数据统计日期错误的问题。
内存占用达到100m是第一次启动软件就这样还是运行了一段时间后才升到100m的呢？
双屏自定义的时候需要在两个屏幕都更改并且分别在右上角都点保存。
自定义颜色保存会尽快加上。

**Comment by mifenfeifen** [comment]
# 数据统计
已经下载新的文件了，明天给反馈

# 内存占用
我怀疑是UI显示消耗内存，然后被缓存下来了，所以分几次试验了下。
1. 刚打开：35M左右
2. 开启选项界面后关闭：接近50M
3. 开启自定义界面后关闭：100+M

同时，我通过`ps`命令查看，增长幅度是类似的，但数值有差异。不过这个我不熟，仅供参考了。
![image](https://user-images.githubusercontent.com/16129288/76274572-04ac5d00-62bc-11ea-97f2-41d8db5c81f5.png)

# 双屏自定义
我知道为什么我操作失败了，因为第二个屏幕显示不全（如图）。

所以这里有个问题：两个屏幕大小不同，但可能显示时是按同样大小，所以其中一个页面溢出到另一个屏幕，导致第一个屏幕显示不全。
（溢出部分我画了分界线）
![image](https://user-images.githubusercontent.com/16129288/76274883-c9f6f480-62bc-11ea-951e-5fa3f19d73cb.png)

**Comment by thelittlepandaisbehind** [comment]
非常谢谢你这次的反馈，内存问题和双屏自定义显示不全问题会在下一次发布更新时修复。

**Comment by mifenfeifen** [comment]
@thelittlepandaisbehind 
目前来看，数据统计问题已经修复成功了。谢谢开发者！

**Comment by mifenfeifen** [comment]
@thelittlepandaisbehind 
我今天看了下，数据统计应该还有问题：
1. 截图时间是15：00，但显示已经用眼17+小时了。
2. 12日的使用情况跟11日是相同（没有重启软件，晚上都是直接休眠电脑），但两者数据相差较大
![image](https://user-images.githubusercontent.com/16129288/76496573-53045c00-6474-11ea-8450-8bb78292a79d.png)

**Comment by thelittlepandaisbehind** [comment]
[Release.zip](https://github.com/Planshit/ProjectEye/files/4323497/Release.zip)
还是修复数据统计的问题，下载试试，麻烦你了

**Comment by mifenfeifen** [comment]
> [Release.zip](https://github.com/Planshit/ProjectEye/files/4323497/Release.zip)
> 还是修复数据统计的问题，下载试试，麻烦你了

嗯嗯，正在试用。不过要到下周一才能提交反馈。

**Comment by thelittlepandaisbehind** [comment]
抱歉，刚刚测试发现之前的程序还是存在统计问题，现在我把修复并且做了电脑睡眠测试没发现问题的更新程序发上来，请用这个测试。😥
[Release20200313.zip](https://github.com/Planshit/ProjectEye/files/4328558/Release20200313.zip)

**Comment by mifenfeifen** [comment]
> 抱歉，测试发现之前上传在这的程序还是存在问题，现在我修复并且做了简单的测试没发现问题，已经发布了版本更新，可以直接在选项中更新或手动下载。

嗯嗯，好的。（刚想反馈问题来着哈哈哈）

**Comment by thelittlepandaisbehind** [comment]
@mifenfeifen 不知道数据统计问题是否已经解决了呢😥

**Comment by mifenfeifen** [comment]
> @mifenfeifen 不知道数据统计问题是否已经解决了呢😥

不好意思啊，一直忘记了。目前来看应该是已经解决了。非常感谢。

**Comment by thelittlepandaisbehind** [comment]
> > @mifenfeifen 不知道数据统计问题是否已经解决了呢😥
> 
> 不好意思啊，一直忘记了。目前来看应该是已经解决了。非常感谢。

不客气，我也要感谢你才能找到这个bug。内存问题依然很头疼，我觉得可能是wpf自身的问题，所以短时间很难解决。

**Comment by thelittlepandaisbehind** [comment]
@mifenfeifen 不好意思打扰一下，是否有时间帮我测试一下“屏幕显示不全”的问题呢？如果可以的话下载附件的程序，进入自定义全屏提示界面，看看是否正常，谢谢。期待你的反馈。**需要注意的是不要覆盖现在的版本，请在一个新目录下运行。**
[TEST_2020_04_08_Release.zip](https://github.com/Planshit/ProjectEye/files/4448822/TEST_2020_04_08_Release.zip)

**Comment by mifenfeifen** [comment]
@thelittlepandaisbehind 主屏看起来是正了，可能是副屏的偏移出错了？

（由于图片上传没成功，只能放到图床上了）：https://imgchr.com/i/GhjmUe

**Comment by thelittlepandaisbehind** [comment]
> @thelittlepandaisbehind 主屏看起来是正了，可能是副屏的偏移出错了？
> 
> （由于图片上传没成功，只能放到图床上了）：https://imgchr.com/i/GhjmUe

非常感谢，今天晚点我会再上传一次更新修复的附件，有时间了再帮我测试一次。然后能否告知一下主副屏的当前分辨率、最大分辨率、缩放比呢

**Comment by mifenfeifen** [comment]
@thelittlepandaisbehind 

# 分辨率
主副屏都是1920*1080分辨率的，但屏幕尺寸不同，主屏15寸，副屏23寸。

# 缩放比例
主屏125%，副屏100%，两者都是系统推荐的比例。

我试着把主屏缩放比例改成100%，发现效果更差了：https://imgchr.com/i/G4SvtS

**Comment by thelittlepandaisbehind** [comment]
@mifenfeifen 

👌谢谢你的反馈。程序暂时没有做修改缩放比实时处理，所以修改缩放比后需要重启软件可能才会正常。

我再次更新了修复（自定义界面显示不全）的代码，请麻烦再测试一次。

> PS：还是注意最好不要覆盖旧版本，在新目录下运行。


[Test_2020_04_11_Release.zip](https://github.com/Planshit/ProjectEye/files/4463923/Test_2020_04_11_Release.zip)

**Comment by mifenfeifen** [comment]
【自定义界面显示不全】这个缺陷已经修复了：https://imgchr.com/i/GXRxbV。撒花！

PS：关于缩放比例的问题，我重启了试试，发现无论是重启软件还是重启系统，都无济于事。只要是调整到非系统推荐的缩放比例，就会造成中心图案的偏移（两个屏幕都是）。但不影响【保存】按钮的显示，也不是什么大问题。：https://imgchr.com/i/GXhk0x

PPS：既然【自定义显示】需要重启软件，那么建议加个【重启软件】的功能。比如可以通过任务栏图标重启，或者在保存显示设置后，询问是否自动重启。当然，由于这个不是高频功能，所以有空再考虑吧。



在 2020-04-11 10:39:42，"Little Panda" <notifications@github.com> 写道：

@mifenfeifen

👌谢谢你的反馈。程序暂时没有做修改缩放比实时处理，所以修改缩放比后需要重启软件可能才会正常。

我再次更新了修复（自定义界面显示不全）的代码，请麻烦再测试一次。

PS：还是注意最好不要覆盖旧版本，在新目录下运行。

Test_2020_04_11_Release.zip

**Comment by thelittlepandaisbehind** [comment]
@mifenfeifen 
感谢你的反馈和测试~
后面应该会去做自动处理缩放，还有加上修改自定义界面免重启。1.2.0更新发布了，欢迎升级。
