### ISSUE TITLE
休息提示页面，休息时间始终显示为20秒

### ISSUE THREAD

**Issue by vlvk** [Planshit/ProjectEye#28]
## 运行环境
- ProjectEye v1.1.6（目前最新）
- OS: Windows 10 1809 64bit

## 问题说明
* 设置休息时长为300秒，而休息时间显示为20秒（如下所示）。

## 设置页面
![图片](https://user-images.githubusercontent.com/21954893/77218307-dd2f7d00-6b64-11ea-827f-6a02083d6d3f.png)

## 提示页面
![图片](https://user-images.githubusercontent.com/21954893/77218286-b2ddbf80-6b64-11ea-9c22-e969c7dfbae1.png)

**Comment by thelittlepandaisbehind** [comment]
😂抱歉，这个是在自定义提醒界面设计中更改的固定文字，在选项>显示>自定义中双击提示文字，可以对它进行修改。有关更多自定义提醒界面的功能在这里可以看到 -> [自定义界面说明](https://github.com/Planshit/ProjectEye/releases/tag/1.1.4)，

**Comment by vlvk** [comment]
OK，明白了。
