### ISSUE TITLE
关于多国语言的翻译邀请

### ISSUE THREAD

**Issue by abadgirlnoa** [Planshit/ProjectEye#32]
🖐大家好，我是应用的开发者🐼小熊猫。

我很希望这个应用能支持多国语言，但是我个人没这个（翻译）能力，如果感兴趣并能提供帮助的朋友（开源项目没有收入所以无法提供经济支持）可以在这个issue里提交翻译。

提供翻译的用户可以在软件的关于页面中加入你的主页链接、名字。

我希望能提供的翻译不是机翻的，而且尽可能简短直白。需要翻译的内容主要是软件所有可见界面出现的文字、提示，以及比较重要的开源仓库readme（暂时不，因为还需要更新）。

谢谢。😋

> 参与翻译请下载附件中的中文文档（文档中出现的所有字词除了占位符和序号外都需要翻译）进行翻译并重新上传到此issue，记得备注你的名字和链接（不然我无法在贡献者中添加你的名字）。有些中文字词可能不适合翻译或者不能很好地表达出功能的作用，所以当你碰到这种情况可以进行更正。

附件整理中...

**Comment by hiliangchunrui** [comment]
刚接触GitHub，不太清楚如何操作。

我觉得是不是有一个文档，汇总了所有需要翻译的文字。这样可能比较方便操作和对比。

**Comment by thelittlepandaisbehind** [comment]
@hiliangchunrui 
好的，我会尽快整理需要翻译的文字发上来，谢谢

**Comment by mr-south-guo** [comment]
我使用了你的软件一段时间了，非常喜欢。我在美国留学过，英语还凑合，很愿意协助你做英语的翻译。

**Comment by thelittlepandaisbehind** [comment]
> 我使用了你的软件一段时间了，非常喜欢。我在美国留学过，英语还凑合，很愿意协助你做英语的翻译。

@mr-south-guo 非常感谢，我会尽快整理需要翻译的文字。

**Comment by thelittlepandaisbehind** [comment]
@hiliangchunrui @mr-south-guo 我已经上传了需要翻译的字词文档，麻烦各位了~

**Comment by mr-south-guo** [comment]
好的。不过这几天比较忙，争取周末翻译前3个文档出来。

**Comment by hiliangchunrui** [comment]
@thelittlepandaisbehind @mr-south-guo   暂时翻译了这两个文档，烦请斧正
[状态栏菜单.txt](https://github.com/Planshit/ProjectEye/files/5205795/default.txt)
[选项窗口.txt](https://github.com/Planshit/ProjectEye/files/5205796/default.txt)

**Comment by mr-south-guo** [comment]
翻译了前3个文档，另外在 @hiliangchunrui 的翻译基础上做了些修改。
[ProjectEye-strings-en.zip](https://github.com/Planshit/ProjectEye/files/5212450/ProjectEye-strings-en.zip)

**Comment by thelittlepandaisbehind** [comment]
@hiliangchunrui @mr-south-guo 非常感谢两位的协助~
