### ISSUE TITLE
支持暗色的全屏提醒

### ISSUE THREAD

**Issue by misdake** [Planshit/ProjectEye#4]
我平时使用电脑时主要用深色背景的软件，突然弹出来全屏的白色内容，有点刺眼
期望能提供一套深色的，供用户选择

**Comment by thelittlepandaisbehind** [comment]
了解，已加入1.0.4版本的开发计划。

**Comment by thelittlepandaisbehind** [comment]
@misdake 
包含暗色主题的1.0.4版本已经发布，如果测试暗色主题没问题后麻烦关闭此issue。[查看1.0.4版本](https://github.com/Planshit/ProjectEye/releases/tag/1.0.4)
