### ISSUE TITLE
双显示器的黑夜模式显示不一致

### ISSUE THREAD

**Issue by a-bad-apple** [Planshit/ProjectEye#41]
笔记本接显示器，在黑夜模式下，显示器是黑色，笔记本屏幕是白色。

**Comment by thelittlepandaisbehind** [comment]
是全屏提示界面显示不一致吗？如果是可以在选项> 显示 > 全屏提示界面自定义中自行修改颜色，需要注意的是每个显示器、每个主题的全屏提示界面都是独立的，修改哪个显示器就在哪个显示器右上角点保存。

还有就是修改深色模式的界面需要先在选项中选中深色主题（无需应用），再进入自定义界面修改。

没有正确创建多显示器的界面这个Bug在下一次更新时会修复，谢谢反馈。

**Comment by a-bad-apple** [comment]
谢谢指导，通过界面自定义，问题已经解决了。
