### ISSUE TITLE
勾选全屏游戏时跳过休息后，就永远不再弹出提示休息

### ISSUE THREAD

**Issue by Super-pixle** [Planshit/ProjectEye#45]
勾选全屏游戏时跳过休息后，不论是不是全屏游戏或者全屏看视频，都不再会提示休息（一直默认跳过），重启电脑以后也是默认跳过。必须取消勾选后才能恢复正常。平常我的场景就是chrome最大化（不是全屏），potplayer最大化（也不是全屏）。

**Comment by thelittlepandaisbehind** [comment]
有没有连接多个显示器呢？

**Comment by Super-pixle** [comment]
没有，就一个显示器

**Comment by thelittlepandaisbehind** [comment]
我尝试修复了，用这个压缩包内的文件覆盖你本地的文件测试一下看看是否有效。[ProjectEye.zip](https://github.com/Planshit/ProjectEye/files/4579624/ProjectEye.zip)

**Comment by Super-pixle** [comment]
使用了几个小时，现在看来问题是修复了
