### ISSUE TITLE
单日时间统计28hours

### ISSUE THREAD

**Issue by wuliGGG** [Planshit/ProjectEye#47]
![image](https://user-images.githubusercontent.com/32957949/81203630-bfc24f80-8ffa-11ea-8ffb-96758b61aab4.png)

**Comment by thelittlepandaisbehind** [comment]
谢谢反馈。是不是周一晚上持续工作到了0点后呢？有没有复现的步骤呢？

**Comment by wuliGGG** [comment]
应该是过了0点，但是周二周三也是持续到零点后，暂时没法复现。

**Comment by thelittlepandaisbehind** [comment]
@wuliGGG 好的。那么周二周三的统计是否正确呢？

**Comment by wuliGGG** [comment]
应该是没有问题的

**Comment by thelittlepandaisbehind** [comment]
好的，谢谢反馈，我会在下一次发布更新时修复

**Comment by thelittlepandaisbehind** [comment]
发布了1.2.8版本，请尝试更新测试

**Comment by thelittlepandaisbehind** [comment]
请问还在使用吗？是否还存在统计的时间异常的问题呢？

**Comment by wuliGGG** [comment]
最近忙毕设，暂时没用

**Comment by thelittlepandaisbehind** [comment]
好的，那这个issue关了，后续有问题再提交
