### ISSUE TITLE
界面错位与能否加入鼠标活动时间与键盘活动时间？

### ISSUE THREAD

**Issue by 2220209876** [Planshit/ProjectEye#48]
1
![image](https://user-images.githubusercontent.com/7346652/81496929-c5b37b80-92ed-11ea-93db-e4950c9ee137.png)
Windows 10 X64系统下

2 可以增加像 https://github.com/rcaelers/workrave 下图的统计功能吗？
![image](https://user-images.githubusercontent.com/7346652/81496959-f09dcf80-92ed-11ea-8c4b-fbdce15efca3.png)
![image](https://user-images.githubusercontent.com/7346652/81496963-f72c4700-92ed-11ea-953b-7f07da0de278.png)
 3 统计增加 日视图

**Comment by thelittlepandaisbehind** [comment]
谢谢你的反馈。

1，不是“界面错位”，因为数据过少的原因，当运行到一定时间就不会“错位”了；
2，除了活动，统计包含的数据是差不多的；鼠标数据的统计跟Project Eye的定位有冲突，我不希望它变得脓肿，只做一个简洁的软件。
3，日视图之前有考虑过，但是可能暂时没有计划增加。当日的数据无非是工作时间、休息次数、跳过次数，而这些在周视图中会以一个三角形标记出来，所以其实算是有的。单独分到一个新页面可能会比较鸡肋。

目前我认为是这样的，欢迎继续讨论~

**Comment by 2220209876** [comment]
![image](https://user-images.githubusercontent.com/7346652/81499819-c9043280-9300-11ea-8b54-edcb612227da.png)
功能不臃肿内存臃肿(┬＿┬)

**Comment by thelittlepandaisbehind** [comment]
😭暂时没办法，WPF是出了名的内存怪兽，加上我个人能力问题短时间可能降不下来
