### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Chuncy-97** [Planshit/ProjectEye#50]
希望可以提供类似番茄钟的功能。
例如 工作20分钟休息一小段时间，两个循环后可以休息更长时间。
这样一个软件就可以满足较多的使用需求了，就不用再去安装一个番茄钟了。
希望开发者可以考虑一下，如果好用，部分功能收费也是可以接受的。
谢谢

**Comment by thelittlepandaisbehind** [comment]
其实很早就考虑过这个功能了，但是想到和软件的命名有点冲突就纠结要不要做😐

**Comment by Chuncy-97** [comment]
这样的番茄钟一部分是为了提高工作效率，另一部分也是为了保护眼睛啊😁

**Comment by thelittlepandaisbehind** [comment]
@Chuncy-97 
也是，希望能在下一次发布更新时完成这个功能。

**Comment by thelittlepandaisbehind** [comment]
@Chuncy-97 
加入了番茄时钟功能的1.3.0版本已经发布，欢迎测试使用

**Comment by Chuncy-97** [comment]
好的，Thanks♪(･ω･)ﾉ😁

**Comment by thelittlepandaisbehind** [comment]
@Chuncy-97 请问还有在使用吗？有没有改进建议？

**Comment by Chuncy-97** [comment]
还在使用，我自己觉得可以改进的地方主要有三个
第一、建议循环次数可以自定义
第二、希望番茄钟休息也可以选择全屏
第三、休息后再次进入工作希望可以有铃声提醒，或全屏提示
目前就这些，功能挺好用的，谢谢您的付出😁

**Comment by thelittlepandaisbehind** [comment]
收到，下一次更新时将更加完善(ง •_•)ง

**Comment by thelittlepandaisbehind** [comment]
@Chuncy-97 
新的1.3.1版本已经发布了，番茄时钟的提示音已经加入了，欢迎更新。但是全屏提示和自定义循环次数在综合考虑和实际测试后发现并不实用或符合番茄时钟，所以没加入。

**Comment by lisansas** [comment]
提两个番茄钟的建议 
1 番茄钟的托盘可以直接通过渐变显示剩余时间 如pomotroid
2 番茄钟的强制提示太大太丑了 建议可以设置不弹出来 

关于原版的建议
建议没有操作PC的时候不统计时间 我没有关电脑的习惯 打开数据统计以后对我没要操作电脑的时间也进行了统计并且提示跳过
