### ISSUE TITLE
建议：增加一个休息一下的选项

### ISSUE THREAD

**Issue by hiliangchunrui** [Planshit/ProjectEye#52]
软件功能实用，我很喜欢。

我想是不是可以增加一个“休息一下”的选项。有时因为一些原因，对软件进行了暂停。暂停结束后，其实很需要休息一下。所以不知道是不是也会有人有类似的需求。休息一下之后，就开始新一轮的“20-20-20”的循环。

**Comment by thelittlepandaisbehind** [comment]
谢谢你的喜欢和建议。

其实我建议暂停后重新恢复前可以离开电脑自行休息，然后再恢复提醒。增加这个功能感觉只是为了让数据统计多一些休息的数据，必要性不大。

**Comment by hiliangchunrui** [comment]
我觉得有这样的功能比较方便，不需要自己额外在考虑休息的时长。

你的建议也是可行的。谢谢
