### ISSUE TITLE
关于跳过休息

### ISSUE THREAD

**Issue by codeofjackie** [Planshit/ProjectEye#54]
使用Win+Tab键可以跳过休息，建议改为不可跳过时锁键盘

**Comment by thelittlepandaisbehind** [comment]
> 使用Win+Tab键可以跳过休息，建议改为不可跳过时锁键盘

那就有点流氓了，如果程序出问题或确实有紧急的事需要切掉怎么办。我觉得软件要做的是辅助，更多需要靠自己自律为主比较好，养成好的习惯，而不是让软件控制你的习惯。
