### ISSUE TITLE
System.Reflection.TargetInvocationException: 调用的目标发生了异常

### ISSUE THREAD

**Issue by maxwellhouse102** [Planshit/ProjectEye#58]
[2021-04-25 22:39:56] [ERROR]
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.DllNotFoundException: 无法加载 DLL“Shcore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 ProjectEye.Core.ScreenExtensions.GetDpiForMonitor(IntPtr hmonitor, DpiType dpiType, UInt32& dpiX, UInt32& dpiY)
   在 ProjectEye.Core.ScreenExtensions.GetDpi(Screen screen, DpiType dpiType, UInt32& dpiX, UInt32& dpiY)
   在 ProjectEye.Core.WindowManager.GetSize(Screen screen)
   在 ProjectEye.Core.WindowManager.CreateWindow(String name, Boolean isMaximized, Boolean newViewModel)
   在 ProjectEye.Core.Service.MainService.CreateTipWindows()
   在 ProjectEye.Core.Service.MainService.Init()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 ProjectEye.Core.Service.ServiceCollection.Initialize()
   在 ProjectEye.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
------------------------

**Comment by 913650629** [comment]
兄弟你也是win7吧，我也碰到这种情况了

**Comment by 913650629** [comment]
而且从网上找的都不能用shcore.dll都不能用，还是会报错

**Comment by noberumotto** [comment]
@maxwellhouse102 @913650629 
非常抱歉！在1.2.0版本开始我加入了一个win7系统不支持的组件（当时没发现）所以目前的解决方法是请使用1.2.0以下的版本

**Comment by 913650629** [comment]
谢谢您啦，这个软件我在win10上用的很喜欢，谢谢作者的付出呀。我先去用1.20版本的来试一试！

**Comment by noberumotto** [comment]
抱歉久等，修复了的版本1.3.7已发布，请尝试下载测试，如果已解决请麻烦关闭这个问题~

**Comment by maxwellhouse102** [comment]
非常好，感谢作者做出这么好的软件，看得出很用心，真了不起
