### ISSUE TITLE
这几个设置没有效果？

### ISSUE THREAD

**Issue by klxq520** [Planshit/ProjectEye#59]
![BaiduShurufa_2021-5-6_20-10-58](https://user-images.githubusercontent.com/45682501/117296134-48dac380-aea7-11eb-81b6-a42909e5a84f.png)
我用potplayer全屏播放时还是会提醒，加入进程也一样，是不是哪里操作错了？

**Comment by noberumotto** [comment]
不需要加.exe

**Comment by 913650629** [comment]
大佬大佬，这种情况是怎么解决呢，系统是win7企业版，System.DllNotFoundException: 无法加载 DLL“Shcore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

**Comment by klxq520** [comment]
> 不需要加.exe

一样无效啊，加不加都照样会提醒

**Comment by noberumotto** [comment]
抱歉久等，尝试修复了的版本1.3.7已发布，请尝试更新测试，如果已解决请麻烦关闭这个问题~
