### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Twinkl4** [Planshit/ProjectEye#60]
这款护眼软件实在是太棒了，感觉美中不足的是系统托盘右键显示比较模糊，在虚拟机里面测试也是这样子😄
![image](https://user-images.githubusercontent.com/61727188/128139881-d87cddc0-88ca-4646-9b53-85ee63ab7bd9.png)

**Comment by noberumotto** [comment]
收到反馈。麻烦告知一下您使用的显示器分辨率和缩放比是多少呢

**Comment by noberumotto** [comment]
修复了这个问题的版本1.4.0已经发布，请记得更新~
