### ISSUE TITLE
是否需要云端同步数据功能？

### ISSUE THREAD

**Issue by noberumotto** [Planshit/ProjectEye#61]
看下有多少人需要吧，超过30人就做。需要请点👍

**Comment by sbsyrqlblx2** [comment]
推荐用坚果云进行数据同步，不得不说这是我用起来最舒服的相关软件

**Comment by noberumotto** [comment]
> 推荐作者大大如果可以的话，能做一个数据统计导出的功能，也可以采用坚果云等进行云端数据同步
> 最后对作者的持续性更新、用爱发电表示感谢！不得不说这是我用起来最舒服的相关软件之一！

谢谢您的认可。数据导出希望是什么格式呢？

**Comment by sbsyrqlblx2** [comment]
> > 推荐作者大大如果可以的话，能做一个数据统计导出的功能，也可以采用坚果云等进行云端数据同步
> > 最后对作者的持续性更新、用爱发电表示感谢！不得不说这是我用起来最舒服的相关软件之一！
> 
> 谢谢您的认可。数据导出希望是什么格式呢？

个人觉得，导出为xlsx，能自己用Excel做一些读取分析就很棒了~

**Comment by noberumotto** [comment]
> > > 推荐作者大大如果可以的话，能做一个数据统计导出的功能，也可以采用坚果云等进行云端数据同步
> > > 最后对作者的持续性更新、用爱发电表示感谢！不得不说这是我用起来最舒服的相关软件之一！
> > 
> > 
> > 谢谢您的认可。数据导出希望是什么格式呢？
> 
> 个人觉得，导出为xlsx，能自己用Excel做一些读取分析就很棒了~

收到
