### ISSUE TITLE
感谢与提建议

### ISSUE THREAD

**Issue by qitiandashengsunwukong** [Planshit/ProjectEye#62]
非常感谢开发者提供的优秀软件体验。使用ProjectEye已经一年多了，提一个功能建议。
我希望在数据统计页本周视图中，柱状图右侧的图片支持自定义功能（coffee_lover，office_work_等）。如在工作时长柱状图右侧看到自己制作的图片提示语“将来的你将会感谢现在奋斗的你”，亦或是在休息卡片右侧看到提示语“你这个年龄段你睡得着觉”。通过此手段能够幽默地勉励自己，提高工作效率。
期待开发者继续维护，十分感谢，送上一杯咖啡~

**Comment by noberumotto** [comment]
收到，谢谢。这个功能在下一个版本中加入~再次感谢你的支持
