### ISSUE TITLE
桌面快捷方式点击后弹出“已停止工作”

### ISSUE THREAD

**Issue by gaadinbav** [Planshit/ProjectEye#7]
如题，1.09版本，系统是LTSB2016，选项里创建桌面快捷方式，之后点击桌面的快捷方式都是显示“Project Eye 已停止工作”。

**Comment by gaadinbav** [comment]
补充一下，我是在Project Eye启动的情况下再点击快捷方式的，没开的情况下是启动Project Eye，如果快捷方式只是启动程序的话，可以加入测试是否已运行吧？

**Comment by thelittlepandaisbehind** [comment]
@gaadinbav 可能是系统的原因我无法复现问题，放不方便留个邮箱我给你发送一个可以拦截错误并记录的版本，然后把错误日志发送给我定位问题呢

**Comment by thelittlepandaisbehind** [comment]
@gaadinbav 你给我发送一封邮件，我会把程序发到你邮箱。heis@thelittlepandaisbehind.com

**Comment by thelittlepandaisbehind** [comment]
@gaadinbav 无法成功复现问题。重复运行检测已经有了。晚些时候会发布一个更新，可以记录错误，方便定位问题。到时候麻烦你下载更新，重新操作复现这个问题，然后把错误日志内容贴上来

**Comment by gaadinbav** [comment]
> 
> 
> @gaadinbav 无法成功复现问题。重复运行检测已经有了。晚些时候会发布一个更新，可以记录错误，方便定位问题。到时候麻烦你下载更新，重新操作复现这个问题，然后把错误日志内容贴上来

好的，日志存放在哪里呢？

**Comment by gaadinbav** [comment]
> 
> 
> @gaadinbav 无法成功复现问题。重复运行检测已经有了。晚些时候会发布一个更新，可以记录错误，方便定位问题。到时候麻烦你下载更新，重新操作复现这个问题，然后把错误日志内容贴上来

1.0.10已无此问题。
