### ISSUE TITLE
还原设置

### ISSUE THREAD

**Issue by xianerhello** [Planshit/ProjectEye#70]
你好，软件选项中的设置可以还原为最开始的吗？

**Comment by noberumotto** [comment]
删除 data\config.xml 文件重启软件即可

**Comment by xianerhello** [comment]
> 删除 data\config.xml 文件重启软件即可



> 删除 data\config.xml 文件重启软件即可

好的👌

**Comment by xianerhello** [comment]
> 删除 data\config.xml 文件重启软件即可

好的👌
