### ISSUE TITLE
关于暂停

### ISSUE THREAD

**Issue by xianerhello** [Planshit/ProjectEye#71]
建议增加工作时间及番茄时钟的暂停选项，中途有事离开的话可以暂停

**Comment by noberumotto** [comment]
当你离开电脑后就表示处于放松双眼/中断工作（打破了番茄工作法则）的状态了，“暂停”这个概念不应该存在的

**Comment by xianerhello** [comment]
我是说离开了，但是计时还在继续

**Comment by noberumotto** [comment]
理论上离开后5分钟不管是用眼计时还是番茄时钟都会停止并进入睡眠状态，难道没有正确工作吗？

**Comment by xianerhello** [comment]
> 理论上离开后5分钟不管是用眼计时还是番茄时钟都会停止并进入睡眠状态，难道没有正确工作吗？

哦，是这样。请问5分钟这个时间可以自己调整吗？

**Comment by noberumotto** [comment]
目前是不能调整，已经写死了。

**Comment by xianerhello** [comment]
> 目前是不能调整，已经写死了。

好的，感谢！
