### ISSUE TITLE
感谢开发。有个建议，休息跳过，能否增加一个推迟3分钟？

### ISSUE THREAD

**Issue by elegantwww** [Planshit/ProjectEye#76]

**Comment by noberumotto** [comment]
抱歉无法增加此功能。推迟代表你已经超时用眼了，那就失去了提醒的意义，“推迟”这个概念是不合理且不应该存在的。ProjectEye 的存在是为了培养和改善用眼习惯，为了自己的双眼一定要记得按时休息~
