### ISSUE TITLE
win11 无法显示全屏弹窗

### ISSUE THREAD

**Issue by ayasechan** [Planshit/ProjectEye#77]
系统版本 win11 22h2
软件版本 1.4.3

时间到了之后可以弹出全屏窗口
但是看不见
使用任务视图就可以看到多了一个 projecteye 的窗口

---

另外请教下怎么抓取日志
我没找到相关的设置或者日志文件

**Comment by noberumotto** [comment]
是否修改（自定义）过窗口的UI呢？如果有修改的话尝试恢复到默认UI看看是否正常，恢复默认全屏窗口UI的方法：删除 `ProjectEye根目录\UI\` 整个文件夹。同时建议将设置也恢复默认：删除 `ProjectEye根目录\Data\config.xml` 文件。

日志文件存放在 `ProjectEye根目录\Log\` 下。

如果以上无法解决此问题还可以尝试下载较旧版本使用。

`1.4.3` 版本已经在 `Windows11 专业版 22H2` 上使用测试没有问题。

**Comment by ayasechan** [comment]
感谢大佬的回复 删除相关文件后问题解决了
