### ISSUE TITLE
提些小建议

### ISSUE THREAD

**Issue by githubcatheaven** [Planshit/ProjectEye#78]
首先非常感谢作者提供这个工具。
一直在找专注工具，或者叫番茄钟，或者叫保护眼睛，不管什么名字，核心功能是类似的。
提些小建议，希望考虑，谢谢。

1. 提供精简版（超小exe，超小内存占用）
2. 精简版功能：只有番茄钟，可自定义工作、休息时间。没了。

**Comment by noberumotto** [comment]
如果您使用windows10以上系统，在时钟应用中自带了番茄时钟的功能哦
