### ISSUE TITLE
建议提供提醒的显示方式设置

### ISSUE THREAD

**Issue by xuchkang171** [Planshit/ProjectEye#8]
一般情况下，比如在做些文本工作，看到提示后，接受或拒绝点相应按钮即可，提醒的显示方式不影响。

但是，比如正在看剧的时候，看到护眼提示后，希望选择「好的」，但点它之前想暂停播放。而现有的全屏指定提醒让我没法儿这么做，于是看剧时常因为这个原因拒绝休息提醒。

所以希望有个「全屏/窗口」的可设置项？

或者加个「提醒界面可鼠标穿透（除按钮）」的选项也不错。或者……也许更好的设计是，全屏提醒出现后，除两个按钮固定不透明显示外，随着鼠标的移动，以鼠标为圆心的一定范围内提醒界面变透明并可穿透，用户如有需要可暂停相应事务。

嗯，总结来说，三种可以考虑的改进方案：

1) 「全屏/窗口」选项？：可选窗口化显示（比如右下角，置顶，但不影响操作其他窗口）；或者

2) 「鼠标穿透」选项？：维持现有透明度，但除按钮以外的提醒窗口可鼠标穿透（+文字提示？）；或者

3) 「鼠标穿透」选项？：维持现有透明度，但除按钮以外的提醒窗口可鼠标穿透，动态使鼠标周边完全可见以暗示可操作。

一点建议。感谢开发这个项目。小工具，大用处。

**Comment by thelittlepandaisbehind** [comment]
@xuchkang171 

很好的建议，计划加入到1.1.0版本中。我会去尝试这几种方案的实际体验情况。

你觉得在提醒前先在右下角或者其他地方像通知（或者小窗口）一样弹出一个预提醒，让用户有一点时间准备，在预提醒结束后才会弹出全屏提示怎么样？

**Comment by gaadinbav** [comment]
建议很好啊，我提下建议，提示可以做成这样：
**右下角小弹窗询问**，列出2选择，**1休息2暂停**，在用户选择前，弹窗置顶不消失，若是用户需要一点时间暂停现在的工作，那么就可以在弹窗驻留的时候处理完；或者在此基础上**可以加入自动处理倒计时**，而这个自动处理有2种，1是若干秒（若干秒可以咨询用户意见或由作者决定，可以的话做成让用户自己设置最好，下面说到的若干秒同此）后自动全屏进入休息，2是若干秒后自动跳过并出现短暂的弹窗提醒说“最好休息一下，保护眼睛”之类的“警示，这2种自动处理也是可以给用户自行设置。另外，lz说到的鼠标穿透我认为不好，因为突然出现全屏覆盖，如果还有鼠标穿透那很容易会在“慌乱中”**误操作**，十分不便。

**Comment by gaadinbav** [comment]
1.0.12，建议一个细节更改
希望自定义文字提醒的用眼时长变量{t}可以支持叠加，也就是跳过或暂停之后，用眼时长可以叠加起来，离开的时间也是

**Comment by thelittlepandaisbehind** [comment]
@gaadinbav 嗯，下一次小更新会加入当天用眼总时长、总休息时长、总跳过次数三个变量。离开的时间我不太明白？

**Comment by gaadinbav** [comment]
> 
> 
> @gaadinbav 嗯，下一次小更新会加入当天用眼总时长、总休息时长、总跳过次数三个变量。离开的时间我不太明白？

离开的时间这个我可能有点误会了，本来我是想说，

- 如果我“用眼”10分钟然后离开了，判断离开了，之后再接着“用眼”，那可以把这两段时间合起来计算；

但是想想其实这中途离开的话，两段时间就构不成“连续用眼”了，所以不应合起来计算，所以无视这个离开时间吧。
