### ISSUE TITLE
作者您好，有个需求 帮看下 谢谢~

### ISSUE THREAD

**Issue by lyeeo** [Planshit/ProjectEye#83]
提示的窗口，可以做个选项
弄一个 小窗口（可以移动）的么，在屏幕的右下角显示提示
有利于
1、出现提示后，需要有正在弄的东西，差一点，可以先做完，之后再点击休息，全屏的话，无法操作
2、等工作忙完后，还可以直接点击右下角的窗口进行休息，感觉这样更方便些
谢谢

**Comment by noberumotto** [comment]
可以试试预提醒弹窗 https://littlepanda.gitbook.io/project-eye/zhu-ti-he-xian-shi-xiao-guo/shi-yong-fei-quan-ping-xiu-xi-ti-shi-xiu-xi-yu-ti-xing

**Comment by lyeeo** [comment]
好的，谢谢~
