### ISSUE TITLE
请问如何在看YouTube视频的时候忽略软件提示呢？

### ISSUE THREAD

**Issue by zhl111** [Planshit/ProjectEye#84]
经常在看到兴起时跳出弹窗，想是否能忽略此类场景，谢谢

**Comment by noberumotto** [comment]
请问是全屏观看吗？如果是可以支持在全屏时不打扰，在选项，行为中可以开启

**Comment by noberumotto** [comment]
如果窗口化观看暂时不支持跳过，只能建议看视频时在右下角图标上右键开启 暂不打扰
