### ISSUE TITLE
安卓

### ISSUE THREAD

**Issue by XXXX-L20** [Planshit/ProjectEye#86]
老板能开发一个安卓版本吗？跪求安卓版，可以接受付费。只求有20-20-20的提醒

**Comment by noberumotto** [comment]
安卓很多类似的app呀

**Comment by XXXX-L20** [comment]
> 安卓很多类似的app呀

我安卓就找到一个20秒护眼，但是通知和时间计算有点问题...我下载了谷歌里边的一些相似软件，都是时间计算或者通知有问题，20分钟后不会主动提醒。老板有推荐的安卓app吗？感谢~~~我找了好几个月了哈哈哈哈哈

**Comment by noberumotto** [comment]
没有ε=(´ο｀*)))唉 我主力机是苹果，自带了提醒功能
